ops4j/org.ops4j.pax.web

pax-web-extender-war/src/main/java/org/ops4j/pax/web/extender/war/internal/parser/WebAppParser.java

PAXWEB-874 Changed bundle.getEntry to bundle.findEntries

---

pax-web-jetty-bundle/pom.xml
pax-web-jetty/pom.xml

See https://ops4j1.jira.com/browse/PAXWEB-898
This adds the missing package imports again.

[PAXWEB-898] - Add missing import packages for SSL

---

pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/ResourceServlet.java

See https://ops4j1.jira.com/browse/PAXWEB-911

[PAXWEB-911] - Performance issue in ResourceServlet that calls twice getResource()

---

pax-web-api/src/main/java/org/ops4j/pax/web/service/WebContainerConstants.java
pax-web-jetty/pom.xml
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactory.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactoryImpl.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/ServerControllerImpl.java
pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/ConfigurationImpl.java
pax-web-runtime/src/main/resources/OSGI-INF/metatype/metatype.xml
pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/Configuration.java

I added support for the following:
1) Configuring an SSL/TLS private key alias because key stores often contain more than one private key entry. https://ops4j1.jira.com/browse/PAXWEB-919
2) Configuring an separate SSL/TLS truststore which is a common use case. https://ops4j1.jira.com/browse/PAXWEB-923
3) Configuring SSL/TLS included/excluded protocols. Because one might want to exclude SSLv3 or TLS 1.0 and TLS 1.1 explicitly for better security. https://ops4j1.jira.com/browse/PAXWEB-922
4) SSL/TLS included/excluded cipher suites. I wanted to back port this 3.2.x is the version that ships with karaf. 
5) I also noticed two issues with the implementation in the master branch for specifying included and excluded cipher suites A) cipher is spelled "cypher" and B) there is a missing "." before …

SSL Improvements

---

pax-web-jsp/pom.xml

add missing package org.apache.tomcat.util.security

PAXWEB-928 Pax Web JSP fails when running with security enabled

---

pax-web-itest/pom.xml

Version 3.2.1 has a CVSS 10.0 vulnerability. That is the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8103
https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

Upgrade Apache Commons Collections to v3.2.2

---

pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/HttpServiceStarted.java

Log exception as error, including cause

[PAXWEB-992] HttpService swallows Exceptions during startup

---

pax-web-deployer/src/main/java/org/ops4j/pax/web/deployer/internal/WarDeployer.java

`WarDeployer` was never really detecting the exploded folder (better yet, it rejected the generated jar file).
The received artifact is never a folder but always a file.

Fix exploded WAR not being handled

---

pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerImpl.java
pax-web-jetty/src/test/java/org/ops4j/pax/web/service/jetty/internal/JettyServerTest.java

https://ops4j1.jira.com/browse/PAXWEB-1001
The same `MBeanContainer` instance needs to be added to and removed from the Jetty server in order for the server to clean up registered MBeans when it's stopped.

[PAXWEB-1001] Old JMX MBeans remain registered even after Pax-Web Jetty is stopped

---

pax-web-features/src/main/resources/features.xml
pax-web-jetty/osgi.bnd

UPDATED: https://ops4j1.jira.com/browse/PAXWEB-1007

[PAXWEB-1007] Jetty Rewrite Handler cannot be used in jetty.xml

---

pax-web-extender-war/src/main/java/org/ops4j/pax/web/extender/war/internal/parser/WebAppParser.java
pax-web-itest/pax-web-itest-base/src/main/java/org/ops4j/pax/web/itest/base/support/TestServlet.java
pax-web-itest/pax-web-itest-base/src/main/java/org/ops4j/pax/web/itest/base/support/TestServletContainerInitializer.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/src/test/java/org/ops4j/pax/web/itest/jetty/WarContainerInitializerIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/src/test/resources/META-INF/services/javax.servlet.ServletContainerInitializer
pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/src/test/resources/web-2.5.xml
pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/src/test/resources/web-3.0.xml
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/ITestBase.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WarContainerInitializerIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/resources/META-INF/services/javax.servlet.ServletContainerInitializer
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/resources/web-2.5.xml
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/resources/web-3.0.xml
pax-web-itest/pax-web-itest-container/pax-web-itest-container-undertow/src/test/java/org/ops4j/pax/web/itest/undertow/WarContainerInitializerIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-undertow/src/test/resources/META-INF/services/javax.servlet.ServletContainerInitializer
pax-web-itest/pax-web-itest-container/pax-web-itest-container-undertow/src/test/resources/web-2.5.xml
pax-web-itest/pax-web-itest-container/pax-web-itest-container-undertow/src/test/resources/web-3.0.xml

- Moved scanning-logik
- Bundle-Classloader adapted by BundleWiring
- Fix accompanied with test using tinybundles instead dedicated sample-project.
- Fixed minor warnings

[PAXWEB-954] Disable Classpath scanning for ContainerInitializers for servlet version < 3

---

pax-web-api/src/main/java/org/ops4j/pax/web/service/WebContainerConstants.java
pax-web-api/src/main/java/org/ops4j/pax/web/service/WebContainerContext.java
pax-web-extender-war/src/main/java/org/ops4j/pax/web/extender/war/internal/WebAppHttpContext.java
pax-web-extender-war/src/main/java/org/ops4j/pax/web/extender/war/internal/WebAppWebContainerContext.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/HttpServiceContext.java
pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/DefaultHttpContext.java
pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/DefaultSharedWebContainerContext.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java
pax-web-undertow/src/main/java/org/ops4j/pax/web/service/undertow/internal/Context.java

In order to pass the ContextName (aka ContextId) down to the containers the interface WebContainerContext was enhanced.
This fix is also relevant for PAXWEB-906 where I currently have no way to match a registered ServletContext with the information available in the runtime.

PAXWEB-1024 Register ServletContext as OSGi-service in all containers

---

pax-web-archetypes/wab-archetype/src/main/resources/archetype-resources/pom.xml

eclipse (verified on neon.2) won't create projects with this archetype (see below). 
---
Unable to create project from archetype [org.ops4j.pax.web.archetypes:wab-archetype:6.0.1]
org.codehaus.plexus.util.xml.pull.XmlPullParserException: start tag unexpected character < (position: START_DOCUMENT seen ...POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n<... @3:2)

move xsi:schemaLocation before the comment

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/TomcatSecureConfigurationIntegrationTest.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/EmbeddedTomcat.java
samples/tomcat-config-fragment/pom.xml
samples/tomcat-config-fragment/src/main/resources/tomcat-server.xml

- don't reconfigure connectors configured in tomcat-server.xml. This is also not done for Jetty
- add a test using a HTTPS connector configured in the tomcat-server.xml
- fix some checkstyle warnings in the newly introduced code

[PAXWEB-630] Further improvements

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WarJSFTCIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WarJsfResourcehandlerIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WarTCIntegrationTest.java
pax-web-tomcat/pom.xml
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java

This pull request does actually three things:
1. Enable el-support in tomcat. For that I had to change two things:
a) The import statements for javax.el in the pom: I copied this from pax-web-jetty. The original statement does not work because with the *-logic bnd will introspect the classes in the bundle and generate imports for all referenced packaged. This does not work when the classes are referenced by reflection API.
b) I created a new ResourceDelegatingBundleClassLoader with the pax-web-tomcat-bundle as parent, that I set as a parentClassloader to a context. pax-web-jetty does someting similar here, anf if I don't do it, the el Factory will not find an implementation.
2. Enable jfaces support in tomcat. The problem is that jfaces creates an internal HashMap for the factories and …

[PAXWEB-993] Fix JSF-Support for Tomcat and enable Tests

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WarJSFTCIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardTCIntegrationTest.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatResourceServlet.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java

This change introduces welcome file support for tomcat. I adapted the coding from the (Jetty) ResourceServlet to the TomcatResourceServlet. I also copied the etag support (which was a to-do in tomcat and is directly adjectant to the welcome file support).
I could revert the uris for the WarJSFTCIntegrationTest back and enable another ignored integration test (that was testing the welcome file).

[PAXWEB-1072] welcome-files support for tomcat

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/CrossServiceIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/HttpCustomContextIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/HttpServiceWithConfigAdminIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/HttpServiceWithoutCMIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/JerseyCustomContextIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/JspSelfRegistrationIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/SharedContextFilterIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/SharedFilterIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/SimultaneousWhiteboardIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WabJettyWebIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WarFormAuthIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WarJSFPrimefacesIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WarJsfCdiIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WebFragmentIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardServletAnnotatedIntegrationTest.java
pax-web-tomcat-bundle/pom.xml

Copy and adapt a reasonable number of integration tests from Jetty to Tomcat
Some features (like filter registration in whiteboard patterns) do not seem to work, but now we have at least tests for those (even though they are ignored for now).

[PAXWEB-1075] Add integration tests for tomcat

---

pax-web-extender-whiteboard/src/main/java/org/ops4j/pax/web/extender/whiteboard/internal/WebApplication.java

Synchronizing the addWebElement method should probably fix the issue if this is the only web application instance used by the whiteboard implementation. Since I'm not really into the code I'm not sure about that and I also don't have a setup to do an integration test.

PAXWEB-1074 Synchronize adding whiteboard web elements

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/HttpServiceWithConfigAdminIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/JerseyCustomContextIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardR6DtoIntegrationTest.java

The tests run locally but some fail on jenkins. This may be a timing issue. This is an attempt to make the tests more robust to timing issues.

[PAXWEB-1075] Try to make integration tests for tomcat more robust

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/HttpServiceWithConfigAdminIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/JerseyCustomContextIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardServletAnnotatedIntegrationTest.java

Try to synchronize with ServletListeners instead of sleep() calls. This will hopefully not break the jenkins build again.

[PAXWEB-1075] Try to use ServletListeners to wait instead of sleep()

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/HttpServiceWithConfigAdminIntegrationTest.java

This is hopefully the final pull request for this. The ServletListeners work in most cases, but not in this particular one (where we reconfigure the server to a different port).

[PAXWEB-1075] ServletListener does not work for server reconfiguration

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WarTCIntegrationTest.java
samples/war/src/main/webapp/WEB-INF/web.xml

Multiple servlet aliases do actually work in tomcat. This pull request just provides a test for this.

[PAXWEB-513] Test for multiple servlet aliases in Tomcat

---

pax-web-itest/pax-web-itest-base/src/main/java/org/ops4j/pax/web/itest/base/client/CookieState.java
pax-web-itest/pax-web-itest-base/src/main/java/org/ops4j/pax/web/itest/base/client/JettyTestClient.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WarJSFPrimefacesIntegrationTest.java

This pull request replaces that hand-crafted cookie handling in the itest client by the one provided by the underlying Jetty HttpClient. In the consequence the CookieState class is just a wrapper for an (in-memory) CookieStore. If present, this CookieStore is set to the Jetty HttpClient and that one will handle all the cookies.
This is important because the test in question does acutally a redirect and without that change the cookies will get lost in the redirect.

[PAXWEB-1078] Fix cookie handling in test client

---

pax-web-jsp/pom.xml

https://ops4j1.jira.com/browse/PAXWEB-1058

Prevent NoClassDefFoundError caused by org/apache/tomcat/InstanceManager

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardDSRestartIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardRestartTCIntegrationTest.java

The test with the Tomcat server fails on the build server. We may need to wait till the servlet is running again before continuing with the test

[PAXWEB-1077] wait till the servlets are up again after bundle restart

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/TomcatResourceConfigurationIntegrationTest.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/EmbeddedTomcat.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/HttpServiceContext.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java
samples/pom.xml
samples/tomcat-config-fragment/src/main/resources/context.xml
samples/war-tomcat-resource/pom.xml
samples/war-tomcat-resource/src/main/java/org/ops4j/pax/web/extender/samples/war/internal/ResourceServlet.java
samples/war-tomcat-resource/src/main/webapp/WEB-INF/web.xml

This patch will allow to configure contexts either with a default context.xml in a configuration fragment or in the configuration directory or with a war specific META-INF/context.xml inside the war.

[PAXWEB-629] Configure Tomcat via context.xml

---

pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java

In plain tomcat the LoginConfig object is created by the web.xml digester and set to the context in the ContextConfig class. In Pax-Web the web.xml is parsed by the extender, so we have to create the LoginConfig ourselves.
We also need to do this in case the authentication valve is defined in the context configuration (which is e.g. necessary if creating a non-default charset on a form valve). In this case the valve still needs to access the information from the context-config (e.g. the login page or the error page).

[PAXWEB-1110] always set loginConfig on context

---

pax-web-features/src/main/resources/features.xml
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/pom.xml
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/ITestBase.java
pax-web-jsp/pom.xml
pax-web-jsp/src/main/java/org/apache/jasper/JspCompilationContext.java
pax-web-jsp/src/main/java/org/apache/tomcat/util/descriptor/tagplugin/TagPluginParser.java
pax-web-jsp/src/main/java/org/ops4j/pax/web/jsp/JspServletWrapper.java
pax-web-tomcat/pom.xml
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/OSGiMemoryRealm.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/EmbeddedTomcat.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/HttpServiceContext.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatResourceServlet.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerFactory.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java
pom.xml
samples/helloworld-jsp/pom.xml

This is the actual update to Tomcat 8.5.20 intended for the master branch and the upcoming pax-web 6.1.x
The changes in detail:
1. Tomcat 8.5.x supports JASPIC and requires the API bundle for that. I added it to the test dependency and the feature.
2. I updated the code copy in pax-web-jsp (this affects only javadoc comments).
3. Another change required in pax-web-jsp. The constant Constants.JSP_FILE does not exist anymore, the request attribute for the jsp file is now named RequestDispatcher.INCLUDE_SERVLET_PATH.
4. the tomcat-embed-juli jar does not exist anymore (I removed the remaining dependencies)
5. Some changes to pax-web-tomcat were required. Actually, the weird host, engine, and service attributes were removed from the tomcat class, so I could remove some code from the …

[PAXWEB-1129] Update to Tomcat 8.5.20

---

pax-web-extender-whiteboard/pom.xml
pom.xml

Enabling Vaadin push on Karaf needed a newer Jetty server. Vaadin push depends on Atmosphere runtime 2.4.11.vaadin2 which needs at least Jetty 9.3.19.v20170502 instead of the 9.3.15.v20161220 that lacks the constructor WebSocketServerFactory(ServletContext, policy) in class org.eclipse.jetty.websocket.server.WebSocketServerFactory.
I upgraded to Jetty 9.3.21.v20170918 and added the missing import-package declaration javax.servlet.annotation; version="[2.3.0,4.0.0)" to pax-web-extender-whiteboard.
This allows annotations like @WebInitParamto to be parsed.

PAXWEB-1133 - Upgrade to latest Jetty 9.3.x

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/HttpServiceWithConfigAdminIntegrationTest.java

Another attempt: It seems when the integration tests fail on Jenkins this is because the actual tests starts too early (before the test servelet is successfully deployed).
A reason might be that the ServletListener misinterprets the start of the default context of the container as the start of the test servlet context and proceeds too early.

[PAXWEB-1075] Try to make Tomcat integration tests more robust on Jenkins

---

pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerImpl.java

Please see my comment on https://ops4j1.jira.com/browse/PAXWEB-1127

Ignore ClassNotFoundException when preloading QueuedThreadPool

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardTCIntegrationTest.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/ContextSelectionHostValve.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/EmbeddedTomcat.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/HttpServiceContext.java

This patch tackles the issue with having multiple HttpContexts with Tomcat.
The 1:1 mapping of a HttpContext to a Catalina Context remains unchanged (I just modified the context name to contain the ID of the WebContainerContext instead of the classname of the HttpContext).
Instead I replaced the Basic valve of the host entity with a new ContextSelectionHostValve. This valve will try to select the correct context in a given list of contexts and call the standard host valve with this context.

[PAXWEB-597] - Allow multiple HttpContext settings for the root URL

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/AsyncServletIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/support/AsyncServlet.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/ContextSelectionHostValve.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/ServiceValve.java

This PR copies the AsyncServletIntegration test from Jetty (including the servlet) and marks the asynchronous test servlets and the valves contained in pax-web-tomcat as supporting asynchronous requests

[PAXWEB-1135] - Async support for Tomcat

---

pax-web-itest/pax-web-itest-common/src/main/java/org/ops4j/pax/web/itest/common/AbstractJspSimpleIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/src/test/java/org/ops4j/pax/web/itest/jetty/JspSimpleIntegrationTest.java

This change actually only re-enables one integration test for other containers than jetty and ignores it for jetty only. I still think that the issue with the integration test should be fixed for jetty.

[PAXWEB-1095] don't ignore JSP test on other containers than Jetty

---

pax-web-extender-war/src/main/java/org/ops4j/pax/web/extender/war/internal/parser/WebAppParser.java

The maxFileSize and maxRequestSize parameter must actually default to -1 (infinite) instead of 0 (which really means 0) as in the default constructor of javax.servlet.MultipartConfigElement

[PAXWEB-1163] WebAppParser uses wrong default values for multipart cfg

---

pax-web-features/src/main/resources/features.xml
pax-web-itest/pax-web-itest-base/src/main/java/org/ops4j/pax/web/itest/base/TestConfiguration.java
pax-web-itest/pax-web-itest-common/src/main/java/org/ops4j/pax/web/itest/common/AbstractWarJsfCdiIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/src/test/java/org/ops4j/pax/web/itest/jetty/CdiIntegrationTest.java
pom.xml

This patch upgrades commons-collections to 3.2.2 and 4.1; this upgrade
had already been done partially, it is completed here. Upgrading to
3.2.2 and 4.1 fixes COLLECTIONS-580, aka CVE-2015-4852, the
deserialization-related RCE.
Release notes:
* https://commons.apache.org/proper/commons-collections/release_3_2_2.html
* https://commons.apache.org/proper/commons-collections/release_4_1.html
Signed-off-by: Stephen Kitt <skitt@redhat.com>

[PAXWEB-1159] Upgrade commons-collections

---

pom.xml

This PR upgrades to ASM 6.2 and Jetty 9.4.10.v20180503 on Pax Web 7.1.x

[PAXWEB-1164] Upgrade to ASM 6.2 and Jetty 9.4.10.v20180503

---

pax-web-api/src/main/java/org/ops4j/pax/web/service/WebContainerConstants.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServer.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerImpl.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerWrapper.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/ServerControllerImpl.java
pax-web-jetty/src/test/java/org/ops4j/pax/web/service/jetty/internal/JettyServerWrapperTest.java
pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/Activator.java
pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/ConfigurationImpl.java
pax-web-runtime/src/main/resources/OSGI-INF/metatype/metatype.xml
pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/Configuration.java

I'm personally going to need to port this back to 7.2.3 for our project but that'll stay on the fork.

[PAXWEB-1180] Add ability to specify a default authMethod and realmName for Jetty Container

---

pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/Configuration.java

Address comments mentioned in: https://groups.google.com/forum/#!topic/ops4j/4XkeOKL7L6k
Provide default methods for the Configuration interface to work with semantic versioning.

[PAXWEB-1180] Fix interface to have a default for versioning

---

pax-web-api/src/main/java/org/ops4j/pax/web/service/WebContainerConstants.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServer.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerImpl.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerWrapper.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/ServerControllerImpl.java
pax-web-jetty/src/test/java/org/ops4j/pax/web/service/jetty/internal/JettyServerWrapperTest.java
pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/Activator.java
pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/ConfigurationImpl.java
pax-web-runtime/src/main/resources/OSGI-INF/metatype/metatype.xml
pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/Configuration.java

Creating 7.2.x PR based on comments: https://groups.google.com/forum/#!topic/ops4j/4XkeOKL7L6k

 [7.2.x] PAXWEB-1180 Add ability to specify a default authMethod and realmName for Jetty Container

---

pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/Activator.java

Fixes a small typo I found when working on a different issue.

Fix a typo when activating the service

---

pax-web-extender-war/src/main/java/org/ops4j/pax/web/extender/war/internal/parser/WebFilterAnnotationConfigurer.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/HttpServiceContext.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerWrapper.java
pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/HttpServiceStarted.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java
pax-web-undertow/src/main/java/org/ops4j/pax/web/service/undertow/internal/Context.java

This fixes a couple of instances where the number of parameters for the log message did not match the number of parameters given to the log method.
Also fixes a few occurrences of incorrect log formatting.

Fix incorrect number of parameters for log messages

---

pax-web-itest/pax-web-itest-base/src/main/java/org/ops4j/pax/web/itest/base/client/JettyTestClient.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/src/test/java/org/ops4j/pax/web/itest/jetty/WebContainerSpdyIntegrationTest.java
pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactoryImpl.java

The main reason behind this PR is to fix a problem with client authentication - https://github.com/eclipse/jetty.project/issues/3554

Stop using deprecated Jetty SslContextFactory constructor

---

pax-web-api/src/main/java/org/ops4j/pax/web/utils/ServletContainerInitializerScanner.java
pax-web-itest/pax-web-itest-common/src/main/java/org/ops4j/pax/web/itest/common/AbstractWebSocketIntegrationTest.java
pax-web-itest/pax-web-itest-common/src/main/java/org/ops4j/pax/web/itest/common/ITestBase.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/pom.xml
pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/src/test/java/org/ops4j/pax/web/itest/jetty/WebSocketIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/pom.xml
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WebSocketIntegrationTest.java
pax-web-itest/pax-web-itest-container/pax-web-itest-container-undertow/src/test/java/org/ops4j/pax/web/itest/undertow/WebSocketIntegrationTest.java
pax-web-tomcat/pom.xml
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/HttpServiceContext.java
pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java
pax-web-tomcat/src/main/resources/META-INF/services/javax.servlet.ServletContainerInitializer
pax-web-tomcat/src/main/resources/META-INF/services/javax.websocket.ContainerProvider
pax-web-tomcat/src/main/resources/META-INF/services/javax.websocket.server.ServerEndpointConfig$Configurator
samples/websocket-jsr356/pom.xml

This pull request contains two commits:
The first one does not contain any productive coding, it only re-enables the websocket integration test for Jetty. On Tomcat and Undertow the tests are still disabled because they fail.
The second commit adds websocket support for the Tomcat container and enables the test for it.

[PAXWEB-1027] Activate Websocket test

---

.travis.yml

Rework the Travis CI tests so that compilation and test execution is done separately and concurrently. It enables Travis CI stages to compile the code and then run jetty, undertow, tomcat and karaf integration
tests in parallel. This prevents the TravisCI tests to fail due to exceeding the maximum run time (50 minutes) for jobs on Travis.
This deprecates PR #231 .

Fix travis ci builds

---

pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/DefaultPropertyResolver.java

A trivial fix to use try-with-resources to make sure the InputStream is closed.

Use try-with-resources in DefaultPropertyResolver

---

pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatResourceServlet.java

The JavaDoc describes that it closes both streams, but it closes none. Simply remove the sentence from JavaDoc.

[javadoc] TomcatResourceServlet copyRange does not close streams

---

pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/pom.xml
pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/pom.xml
pax-web-itest/pax-web-itest-container/pax-web-itest-container-undertow/pom.xml
pax-web-itest/pom.xml
pom.xml
samples/war-jsf-primefaces/pom.xml
samples/war-jsf/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerImpl.java
pom.xml

@ANierbeck concerns a fix for PAXWEB-1274. Please review. As mentioned on the ticket, when upgrading to the new jetty version integration tests registering filters already failed. As such tests are included that cover this change.

PAXWEB-1274 support jetty 9.4.34

---

pax-web-features/pom.xml
pax-web-features/src/main/resources/features.xml
pax-web-keycloak21/keycloak21-common/pom.xml
pax-web-keycloak21/keycloak21-common/src/main/java/org/keycloak/crypto/def/BCOCSPProvider.java
pax-web-keycloak21/keycloak21-common/src/main/resources/META-INF/services/org.keycloak.adapters.authentication.ClientCredentialsProvider
pax-web-keycloak21/keycloak21-common/src/main/resources/META-INF/services/org.keycloak.adapters.authorization.ClaimInformationPointProviderFactory
pax-web-keycloak21/keycloak21-common/src/main/resources/META-INF/services/org.keycloak.common.crypto.CryptoProvider
pax-web-keycloak21/keycloak21-osgi-adapter/pom.xml
pax-web-keycloak21/keycloak21-osgi-adapter/src/main/java/org/keycloak/adapters/osgi/BundleBasedKeycloakConfigResolver.java
pax-web-keycloak21/keycloak21-osgi-adapter/src/main/java/org/keycloak/adapters/osgi/HierarchicalPathBasedKeycloakConfigResolver.java
pax-web-keycloak21/keycloak21-osgi-adapter/src/main/java/org/keycloak/adapters/osgi/PathBasedKeycloakConfigResolver.java
pax-web-keycloak21/pax-web-jetty-keycloak21/pom.xml
pax-web-keycloak21/pax-web-jetty-keycloak21/src/main/java/org/ops4j/pax/web/keycloak/jetty/KeycloakAuthenticatorService.java
pax-web-keycloak21/pax-web-jetty-keycloak21/src/main/resources/META-INF/services/org.ops4j.pax.web.service.AuthenticatorService
pax-web-keycloak21/pax-web-tomcat-keycloak21/pom.xml
pax-web-keycloak21/pax-web-tomcat-keycloak21/src/main/java/org/ops4j/pax/web/keycloak/tomcat/KeycloakAuthenticatorService.java
pax-web-keycloak21/pax-web-tomcat-keycloak21/src/main/resources/META-INF/services/org.ops4j.pax.web.service.AuthenticatorService
pax-web-keycloak21/pax-web-undertow-keycloak21/pom.xml
pax-web-keycloak21/pax-web-undertow-keycloak21/src/main/java/org/ops4j/pax/web/keycloak/undertow/KeycloakAuthenticatorService.java
pax-web-keycloak21/pax-web-undertow-keycloak21/src/main/resources/META-INF/services/org.ops4j.pax.web.service.AuthenticatorService
pax-web-keycloak21/pom.xml
pax-web-keycloak21/readme.adoc
pom.xml

Upgraded repackaged Keycloak 20 libraries to 20.0.5. 
Unable to source Keycloak 18.0.3 releases falling back to the 18.0.2 version.
Added repackaged Keycloak 21 libraries, addresses Pax-Web GitHub issue #1834

Added repackaged Keycloak 21 libraries 21.0.0.

---

pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerWrapper.java

Welcome files are not updated if a Servlet is wrapped into a `org.eclipse.jetty.servlet.ServletHolder.Wrapper` which is the default behaviour for not async servlet `org.eclipse.jetty.servlet.ServletHolder.NotAsync`.

Fix welcome file model change in jetty wrapper

---

pax-web-fragments/pax-web-compatibility-servlet31/pom.xml

Adds missing bundle-version to Fragment-Host of pax-web-compatibility-servlet31 to solve #2005

[#2005] Adds missing bundle-version to Fragment-Host of pax-web-compatibility-servlet31
