pax-web-jetty-bundle/pom.xml
=> PAXWEB-875 Fixed package import

pax-web-spi/pom.xml, pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/util/ResourceDelegatingBundleClassLoader.java, pom.xml
Optimize performance of ResourceDelegatingBundleClassLoader by Caching.
=> PAXWEB-758 and PAXWEB-882

pax-web-api/src/main/java/org/ops4j/pax/web/service/WebContainerConstants.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactory.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactoryImpl.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/ServerControllerImpl.java, pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/ConfigurationImpl.java, pax-web-runtime/src/main/resources/OSGI-INF/metatype/metatype.xml, pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/Configuration.java
See: https://ops4j1.jira.com/browse/PAXWEB-927
=> Refactored properties for ssl keystore password and ssl private key password.

pax-web-api/src/main/java/org/ops4j/pax/web/service/WebContainerConstants.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactory.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactoryImpl.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/ServerControllerImpl.java, pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/ConfigurationImpl.java, pax-web-runtime/src/main/resources/OSGI-INF/metatype/metatype.xml, pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/Configuration.java
https://ops4j1.jira.com/browse/PAXWEB-919
https://ops4j1.jira.com/browse/PAXWEB-923
https://ops4j1.jira.com/browse/PAXWEB-922
https://ops4j1.jira.com/browse/PAXWEB-920
https://ops4j1.jira.com/browse/PAXWEB-921
https://ops4j1.jira.com/browse/PAXWEB-927
=> SSL/TLS features, fixes, and improvements.

pax-web-api/src/main/java/org/ops4j/pax/web/service/WebContainerConstants.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactory.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactoryImpl.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/ServerControllerImpl.java, pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/Activator.java, pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/ConfigurationImpl.java, pax-web-runtime/src/main/resources/OSGI-INF/metatype/metatype.xml, pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/Configuration.java
add ability to enable/disable SSL renogotiation in Jetty container using Pax Web configuration
=> [PAXWEB-951] Add ability to configure SslContextFactory.setRenegotiationAllowed

pax-web-api/src/main/java/org/ops4j/pax/web/service/WebContainerConstants.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactory.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactoryImpl.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/ServerControllerImpl.java, pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/Activator.java, pax-web-runtime/src/main/java/org/ops4j/pax/web/service/internal/ConfigurationImpl.java, pax-web-runtime/src/main/resources/OSGI-INF/metatype/metatype.xml, pax-web-spi/src/main/java/org/ops4j/pax/web/service/spi/Configuration.java
https://ops4j1.jira.com/browse/PAXWEB-951
=> add ability to enable/disable SSL renogotiation in Jetty container

pax-web-api/src/main/java/org/ops4j/pax/web/service/WebContainerConstants.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/src/test/java/org/ops4j/pax/web/itest/jetty/WebContainerIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WebContainerTCIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-undertow/src/test/java/org/ops4j/pax/web/itest/undertow/WebContainerIntegrationTest.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/HttpServiceContext.java, pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java, pax-web-undertow/src/main/java/org/ops4j/pax/web/service/undertow/internal/Context.java
Please review.
Synchronisation is handled by calling methods as far as I saw.
=> PAXWEB-1024 Register ServletContext as OSGi-service in all containers

pax-web-jsp/src/main/java/org/ops4j/pax/web/jsp/TldScanner.java
Support for embedded jars as well as fragments
https://ops4j1.jira.com/browse/PAXWEB-1034
=> PAXWEB-1034

pax-web-descriptor/pom.xml, pax-web-descriptor/src/main/resources/catalog.cat, pax-web-descriptor/src/main/resources/xsd/xml.xsd
https://ops4j1.jira.com/browse/PAXWEB-1068
=> [PAXWEB-1068] pax-web-descriptor does not build without direct internet access

pax-web-extender-whiteboard/src/main/java/org/ops4j/pax/web/extender/whiteboard/internal/ExtendedHttpServiceRuntime.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/pom.xml, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/AuthenticationTCIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/TomcatConfigurationIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardR6DtoIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardTCIntegrationTest.java, pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/EmbeddedTomcat.java, samples/tomcat-config-fragment/src/main/resources/tomcat-server.xml
Add enhancements for PAXWEB-630 and enable some integration tests for the tomcat container
=> [PAXWEB-630] Interpret and use the tomcat-server.xml

pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java
This is the same change is for #104 (only for the pax-web-6.0.x branch)
=> [PAXWEB-1110] always set loginConfig on context

pax-web-manual/src/main/asciidoc/Basic-Configuration.adoc
This option (checkForwardedHeaders) has been implemented a while a go. But the documentation was missing. I just added a short description.
=> [PAXWEB-691] Update manual to with configuration

pax-web-jetty/pom.xml, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/Activator.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactory.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyFactoryImpl.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServer.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerImpl.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/ServerControllerFactoryImpl.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/ServerControllerImpl.java
https://ops4j1.jira.com/browse/PAXWEB-966
=> [PAXWEB-966] Avoid restarting Jetty when new handlers/customizers are introduced

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/SimultaneousWhiteboardIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WebFragmentIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardRestartTCIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardServletAnnotatedIntegrationTest.java, pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java
Activate several other tests for Tomcat that are fixed by the previous commit
One of the newly activated tests revealed an (ignored) NPE, so I added a check for this
=> [PAXWEB-597] - activate more integration tests for Tomcat

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/SimultaneousWhiteboardIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WebFragmentIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardRestartTCIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardServletAnnotatedIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardTCIntegrationTest.java, pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/ContextSelectionHostValve.java, pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/EmbeddedTomcat.java, pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/HttpServiceContext.java, pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java
This is actually the same change as previously merged to the master branch
=> [PAXWEB-597] - Allow multiple HttpContext settings for the root URL

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/SimultaneousWhiteboardIntegrationTest.java
=> [PAXWEB-597] - revert one integration test change

pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardR6DtoIntegrationTest.java
change picked from pax-web-6.1.x and master
=> [PAXWEB-597] - Make integration test more robust

pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/src/test/java/org/ops4j/pax/web/itest/jetty/WarExtendedIntegrationTest.java
This file should not have been changed and was accidentally replaced
by the one from the master branch
=> [PAXWEB-1083] Fix merge error

pax-web-itest/pax-web-itest-common/src/main/java/org/ops4j/pax/web/itest/common/AbstractWhiteboardR6IntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/src/test/java/org/ops4j/pax/web/itest/jetty/WhiteboardR6IntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-tomcat/src/test/java/org/ops4j/pax/web/itest/tomcat/WhiteboardR6IntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-undertow/src/test/java/org/ops4j/pax/web/itest/undertow/WhiteboardR6IntegrationTest.java
This change does acutally not fix the issue but it activates a test for Tomcat that actually shows the issue
=> [PAXWEB-1142] Prepare integration test to demonstrate issue

pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java
I just did a little too much copy and paste from the undertow implementation
=> [PAXWEB-1142] Fix comment

pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/OSGiMemoryRealm.java, pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/EmbeddedTomcat.java, pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatResourceServlet.java, pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/TomcatServerWrapper.java
This just removes some checkstyle and findbugs warning. There is no code changed that is actually called.
=> fix checkstyle and findbugs warnings

pax-web-extender-war/src/main/java/org/ops4j/pax/web/extender/war/internal/parser/WebAppParser.java
Hi,
Please consider my fix for merging. It would be cool if you could merge this fix into other
maintenance branches (e.g. 6.0.x and 6.1.x) too so that it can be picked up by the next karaf releases.
And sorry for not creating a JIRA entry. Unfortunately I was not able to gain access to the ops4j jira...
Thanks and kind regards,
Marc
=> fix NPE while parsing session config

pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/OSGiMemoryRealm.java
closing input stream in finally block
=> [PAXWEB-1177] fix resource leak

pax-web-extender-whiteboard/src/main/java/org/ops4j/pax/web/extender/whiteboard/internal/tracker/AbstractTracker.java, pax-web-itest/pax-web-itest-common/src/main/java/org/ops4j/pax/web/itest/common/AbstractWarJsfCdiIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-jetty/src/test/java/org/ops4j/pax/web/itest/jetty/support/DocumentServlet.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-undertow/src/test/java/org/ops4j/pax/web/itest/undertow/WebFragmentIntegrationTest.java, pax-web-itest/pax-web-itest-container/pax-web-itest-container-undertow/src/test/java/org/ops4j/pax/web/itest/undertow/XmlSslNoAuthIntegrationTest.java, pax-web-itest/pax-web-itest-karaf/src/test/java/org/ops4j/pax/web/itest/karaf/FeaturesKarafTest.java, pax-web-itest/pax-web-itest-karaf/src/test/java/org/ops4j/pax/web/itest/karaf/FeaturesTCKarafTest.java, pax-web-itest/pax-web-itest-karaf/src/test/java/org/ops4j/pax/web/itest/karaf/JspFilterIntegrationTest.java, pax-web-itest/pax-web-itest-karaf/src/test/java/org/ops4j/pax/web/itest/karaf/SpringOsgiKarafTest.java, pax-web-itest/pax-web-itest-karaf/src/test/java/org/ops4j/pax/web/itest/karaf/WarUndertowKarafTest.java, pax-web-itest/pax-web-itest-karaf/src/test/java/org/ops4j/pax/web/itest/karaf/WebConsoleKarafTest.java, pax-web-itest/pax-web-itest-karaf/src/test/java/org/ops4j/pax/web/itest/karaf/WhiteboardKarafTest.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/HttpServiceContext.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerImpl.java, pax-web-jetty/src/main/java/org/ops4j/pax/web/service/jetty/internal/JettyServerWrapper.java, pax-web-jetty/src/test/java/org/ops4j/pax/web/service/jetty/internal/DOMJettyWebXmlParserTest.java, pax-web-jetty/src/test/java/org/ops4j/pax/web/service/jetty/internal/HandlerDestructionTest.java, pax-web-jetty/src/test/java/org/ops4j/pax/web/service/jetty/internal/JettyServerWrapperTest.java, pax-web-jetty/src/test/java/org/ops4j/pax/web/service/jetty/internal/ResourceServletTest.java, pax-web-jsp/src/main/java/org/apache/jasper/JspCompilationContext.java, pax-web-jsp/src/main/java/org/ops4j/pax/web/jsp/InstanceManager.java, pax-web-jsp/src/main/java/org/ops4j/pax/web/jsp/JasperClassLoader.java, pax-web-jsp/src/main/java/org/ops4j/pax/web/jsp/JasperInitializer.java, pax-web-spi/src/test/java/org/ops4j/pax/web/service/spi/model/FilterModelTest.java, pax-web-spi/src/test/java/org/ops4j/pax/web/service/spi/model/ServletModelTest.java, pax-web-undertow/src/main/java/org/ops4j/pax/web/service/undertow/internal/security/PropertiesIdentityManager.java, pax-web-undertow/src/test/java/org/ops4j/pax/web/service/undertow/internal/ResourceServletTest.java, samples/war-jsf22-cdi/src/main/java/org/ops4j/pax/web/samples/warjsf22cdi/Hello.java
These are all minor cleanups that should not affect the code logic anyhow.
=> Minor cleanups

samples/whiteboard-extended/src/main/java/org/ops4j/pax/web/extender/samples/whiteboard/internal/Activator.java
The registered servlets and http context mappings are not unregistered correctly.
=> fix cleanup of whiteboard-extended sample

pax-web-tomcat/src/main/java/org/ops4j/pax/web/service/tomcat/internal/OsgiContextConfiguration.java
This change moves the authenticator valve configuration and instantiation after the context parsing. As in plain tomcat the Tomcat  provided authenticator is only instantiated and added to the context if the context does not already contain an authenticator.
=> Allow to define alternate login valve in Tomcat context.xml
